# Generated by Django 6.0.2 on 2026-03-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmemory',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
